nutanix_subnet_name = "Sandbox_IPAM-Vlan91"
template_name = "Poc-redhat"
cluster_name = "DNKD1VNCT001"
vm_num_sockets = "2"
vm_num_cores_per_socket = "1"
vm_num_threads_per_core = "1"
ChangeNumber = "CHG000003"
location = "deuso"
