name: Run Ansible Playbook

on:
  workflow_dispatch:

jobs:
  run-ansible:
    runs-on: self-hosted

    env:
      user: ${{ secrets.SNOW_USER }}
      password: ${{ secrets.SNOW_PASSWORD }}
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Ansible Installation
        run: ansible --version 2>&1 | tee /tmp/terraform-install.log

      - name: Run ServiceNow Playbook
        run: |
          ansible-playbook nutanix_vm_prov/snow_integration.yml
        
      - name: Verify tfvars file
        run: |
          find . -name "*.tfvars"
          ls -ltr terraform/nutanix_vm_iac/
          
      - name: Verify Terraform Installation
        run: terraform -version 2>&1 | tee /tmp/terraform-install.log        
       
      - name: Terraform Init
        working-directory: terraform/nutanix_vm_iac
        env:
          TF_VAR_prism: ${{ secrets.TF_VAR_PRISM }}
        run: terraform init 2>&1 | tee /tmp/terraform-install.log

      - name: Terraform Plan
        working-directory: terraform/nutanix_vm_iac
        env:
          TF_VAR_prism: ${{ secrets.TF_VAR_PRISM }}
        run: terraform plan -var-file=terraform.tfvars 2>&1 | tee /tmp/terraform-install.log
