name: Run Ansible Playbook

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  run-ansible:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Verify Ansible Installation
        run: ansible --version

      # - name: Run Ansible Playbook
      #   run: |
      #     ansible-playbook \
      #       -i inventory/hosts.ini \
      #       playbooks/site.yml
`
